config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'home#index'
get '/show', to: 'home#show' 
get '/occasions/diwali(/:wisher)', to: 'home#diwali', as: :diwali
get '/occasions/christmas(/:wisher)', to: 'home#christmas', as: :christmas
get '/occasions/holi(/:wisher)', to: 'home#holi', as: :holi
get '/occasions/birthday(/:wisher)', to: 'home#birthday', as: :birthday
get '/occasions/newyear(/:wisher)', to: 'home#newyear', as: :newyear
get '/occasions/choti_diwali(/:wisher)', to: 'home#choti_diwali', as: :choti_diwali

 resources :feedbacks , only: [:new,:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
	def create
		@feedback = Feedback.create(feedback_params)
		if @feedback.save
				redirect_to :back
			else
			    flash[:notice] = "Error in form"
				redirect_to :back
		end
	end
	private

	def feedback_params
		params.require(:feedback).permit(:name,:email,:feedback)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :wisher

def wisher
@wisher = params[:wisher]
@feedback = Feedback.new

end

def index

end

def show

end

def diwali
	
end

def birthday
end

def holi
end

def christmas
end

def choti_diwali
end

def newyear

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_feedback.html.haml
#feedback.modal.fade{'tabindex':-1 , 'role':'dialog','aria-labelledby':'feedback'}
	.modal-dialog.modal-lg{'role':'document'}
		.modal-content.text-center
			#feedback.container
				.text-center.lead
					Give Your Valuable FeedBack
					%br
				= form_for @feedback do |f|
					.form-group
						=f.label :name , class:'h2 '
						= f.text_field :name, class:'form-control'
					.form-group
						=f.label :email , class:'h2 '
						= f.email_field :email, class:'form-control'
					.form-group
						=f.label :what_you_think , class:'h2 '
						= f.text_area :feedback, class:'form-control'
					.form-group
						= f.submit :GiveFeedback , class:'btn btn-lg btn-primary'
					%br

app/views/home/_modaldiv.html.haml
#occasionoption.modal.fade.m{'tabindex':-1 , 'role':'dialog','aria-labelledby':'occasionoption'}
	.modal-dialog.modal-lg{'role':'document'}
		.modal-content.text-center
			.h1 Some of the occasions are

			%ul
				%li=link_to 'Diwali' , diwali_path
				%li=link_to 'Birthday' , birthday_path
				%li= link_to 'New Year' , newyear_path
				%li=link_to 'holi' , holi_path
				%li=link_to 'Christmas' , christmas_path
				%li=link_to 'Choti Diwali' , choti_diwali_path

app/views/home/birthday.html.haml
.decordiv
	.decor_diwali
		.diwaliwish.text-center
			.wishername_diwali
				-if @wisher==nil
					%p 'Your name'
				-else
					=@wisher
			=image_tag 'wish.png' , class: 'diwaliwishimg'
		.birthday_main_decor
			.row
				.birthday_image1.col-xs-5
					=image_tag 'birthday1.gif'
				.birthday_image2.col-xs-6
					=image_tag 'birthday2.gif'
			%br
			.special_message
				%blockquote
					%p 
						On your special day, I wish you good luck. I hope this wonderful day will fill up your heart with joy and blessings. Have a fantastic birthday, celebrate the happiness on every day of your life. Happy Birthday!

					%footer 
						%cite{'title':"Wisher Name"}
							= @wisher
			%form.form-inline.text-center
				.form-group
					%input.form-control{'type':'name','placeholder':'Name',id:'wisher_name'}
					/%input.form-control{'type':'name','placeholder':'Special Message'}
					%btn.btn.btn-success{'id':'wisher_btn'} Wish
					%br
					%hr

					- if @wisher != nil
						%label Share your URL:
						%input.form-control{'type':'url','placeholder':'sharing url','id':'urlinput','value':"#{request.original_url}"}




app/views/home/choti_diwali.html.haml
.decordiv
	.decor_diwali
		.diwaliwish.text-center
			.wishername_diwali
				-if @wisher==nil
					%p 'Your name'
				-else
					=@wisher
			=image_tag 'wish.png' , class: 'diwaliwishimg'
		.birthday_main_decor
			.row
				.birthday_image1.col-xs-6
					=image_tag 'choti_diwali2.gif'
				.birthday_image2.col-xs-6
					=image_tag 'choti_diwali_gif.gif'
			%br
			.special_message
				%blockquote
					%p.lead
						Choti hi sahi,
						Diwali to hai...
						%br
						HAPPY DIWALI

					%footer 
						%cite{'title':"Wisher Name"}
							= @wisher
			%form.form-inline.text-center
				.form-group
					%input.form-control{'type':'name','placeholder':'Name',id:'wisher_name'}
					/%input.form-control{'type':'name','placeholder':'Special Message'}
					%btn.btn.btn-success{'id':'wisher_btn'} Wish
					%br
					%hr

					- if @wisher != nil
						%label Share your URL:
						%input.form-control{'type':'url','placeholder':'sharing url','id':'urlinput','value':"#{request.original_url}"}




app/views/home/christmas.html.haml
.decordiv
	.decor_diwali
		.diwaliwish.text-center
			.wishername_diwali
				-if @wisher==nil
					%p 'Your name'
				-else
					=@wisher
			=image_tag 'wish.png' , class: 'diwaliwishimg'
		.birthday_main_decor
			.row
				.birthday_image1.col-xs-5
					=image_tag 'christmas.gif'
				.birthday_image2.col-xs-6
					=image_tag 'christmasn2.gif' , class:'christmas2img'
			%br
			.special_message
				%blockquote
					%p 
						On your special day, I wish you good luck. I hope this wonderful day will fill up your heart with joy and blessings. Have a fantastic birthday, celebrate the happiness on every day of your life. Happy Birthday!

					%footer 
						%cite{'title':"Wisher Name"}
							= @wisher
			%form.form-inline.text-center
				.form-group
					%input.form-control{'type':'name','placeholder':'Name',id:'wisher_name'}
					/%input.form-control{'type':'name','placeholder':'Special Message'}
					%btn.btn.btn-success{'id':'wisher_btn'} Wish
					%br
					%hr

					- if @wisher != nil
						%label Share your URL:
						%input.form-control{'type':'url','placeholder':'sharing url','id':'urlinput','value':"#{request.original_url}"}



app/views/home/diwali.html.haml
.decordiv
	.decor_diwali
		.diwaliwish.text-center
			.wishername_diwali
				-if @wisher==nil
					%p 'Your name here'
				-else
					=@wisher
			=image_tag 'wish.png' , class: 'diwaliwishimg'
		.diwali_main_decor
			.diwali_image.text-center
				=image_tag 'candle.gif'
			.special_message
				%blockquote
					%p 
						May this joyous festival bring your family a lot of blessings in any form— money, food or whatsoever. Your family deserves such rewards for being a good one all throughout the year.
					%footer 
						%cite{'title':"Wisher Name"}
							= @wisher
			%form.form-inline.text-center
				.form-group
					%input.form-control{'type':'name','placeholder':'Name',id:'wisher_name'}
					%input.form-control{'type':'name','placeholder':'Special Message'}
					%btn.btn.btn-success{'id':'wisher_btn'} Wish
					%br
					%hr

					- if @wisher != nil
						%label Share your URL:
						%input.form-control{'type':'url','placeholder':'sharing url','id':'urlinput','value':"#{request.original_url}"}

app/views/home/holi.html.haml
.decordiv
	.decor_diwali
		.diwaliwish.text-center
			.wishername_diwali
				-if @wisher==nil
					%p 'Your name here'
				-else
					=@wisher
			=image_tag 'wish.png' , class: 'diwaliwishimg'
		.holi_main_decor
			.diwali_image.text-center
				=image_tag 'Holi.gif'
			.special_message
				%blockquote
					%p 
						Let it go, just color it red and yellow and green and purple. Life is letting it go and playing Holi!
					%footer 
						%cite{'title':"Wisher Name"}
							= @wisher
			%form.form-inline.text-center
				.form-group
					%input.form-control{'type':'name','placeholder':'Name',id:'wisher_name'}
					/%input.form-control{'type':'name','placeholder':'Special Message'}
					%btn.btn.btn-success{'id':'wisher_btn'} Wish
					%br
					%hr

					- if @wisher != nil
						%label Share your URL:
						%input.form-control{'type':'url','placeholder':'sharing url','id':'urlinput','value':"#{request.original_url}"}



app/views/home/index.html.haml
#indexmainbg
	.heading.text-center
		Welcome to Wishme-Hub
	%p.lead
		A new way of wishing your family and friends..
		No matter what the occasion is, we all love to wish and to be wished.
	.h3
		Wishme-hub is specially created with love to spread love.
	%br
	%hr
	.row.index_brief.text-center
		.col-xs-4
			=image_tag 'diwali.jpg'
			.h2
				Diwali Wishes
			=link_to 'Wish now' , diwali_path , class:'btn btn-primary' 
		.col-xs-4
			=image_tag 'birthday.gif'
			.h2
				Birthday Wishes
			=link_to 'Wish now' , birthday_path , class:'btn btn-primary' 
		.col-xs-4
			=image_tag 'newyear.jpg'
			.h2
				New year's eve
			=link_to 'Wish now' , newyear_path , class:'btn btn-primary' 
	%hr
	.container
		%ul
			.h4
				%li 
					Select your occasion
				%li
					Write your name
				%li
					Write an optional personal message and you're ready to go.
	%hr
	.text-center{'data-target':'#occasionoption' , 'data-toggle':'modal'}
		='-- >'
		.btn.btn-primary.modallink.grey Start now 
	%hr
= render 'modaldiv'

app/views/home/newyear.html.haml
.decordiv
	.decor_diwali
		.diwaliwish.text-center
			.wishername_diwali
				-if @wisher==nil
					%p 'Your name here'
				-else
					=@wisher
			=image_tag 'wish.png' , class: 'diwaliwishimg'
		.birthday_main_decor
			.diwali_image.text-center
				.row
					.birthday_image1.col-xs-5
						=image_tag 'newyear.jpg'
					.birthday_image2.col-xs-6
						=image_tag 'new year1.gif'
			.special_message
				%blockquote
					%p 
						If the previous year hasn’t given you something to be happy and proud of, don’t fret. If the 31st of December signifies the end of a year, the 1st of January signifies the beginning. You have life; you have hope, go out there and accomplish all that you want.
					%footer 
						%cite{'title':"Wisher Name"}
							= @wisher
			%form.form-inline.text-center
				.form-group
					%input.form-control{'type':'name','placeholder':'Name',id:'wisher_name'}
					/%input.form-control{'type':'name','placeholder':'Special Message'}
					%btn.btn.btn-success{'id':'wisher_btn'} Wish
					%br
					%hr

					- if @wisher != nil
						%label Share your URL:
						%input.form-control{'type':'url','placeholder':'sharing url','id':'urlinput','value':"#{request.original_url}"}



app/views/layouts/application.html.haml
!!!
%html
	%head
		%title
			Wishme Hub
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
		%script{'async':true ,'src':"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
		:javascript
			(adsbygoogle = window.adsbygoogle || []).push({
			google_ad_client: "ca-pub-8656288428865042",
			enable_page_level_ads: true
			});

	%body
		.container-fluid
			.marquee.row
				%marquee.col-xs-1{'direction':'up','scrolldelay:':'5'}
					=image_tag 'diwali1.png' , class:'marquee-left'
					%br
					=image_tag 'diwali2.png' , class:'marquee-left'
					%br
					=image_tag 'diwali1.png' , class:'marquee-left'
					%br
					=image_tag 'diwali2.png' , class:'marquee-left'
					%br
					=image_tag 'diwali1.png' , class:'marquee-left'
					%br
					=image_tag 'diwali2.png' , class:'marquee-left'
					%br
					=image_tag 'diwali1.png' , class:'marquee-left'
					%br
					=image_tag 'diwali2.png' , class:'marquee-left'
					%br
					=image_tag 'diwali1.png' , class:'marquee-left'
					%br
					=image_tag 'diwali2.png' , class:'marquee-left'
					%br
					=image_tag 'diwali1.png' , class:'marquee-left'
					%br
					=image_tag 'diwali1.png' , class:'marquee-left'
					%br
				.middiv.col-xs-10
					.navbar
						.nav.text-center.logo
							=link_to image_tag('logo.png') , root_path
					.text-center{'data-target':'#occasionoption' , 'data-toggle':'modal'}
						.btn.btn-primary See All occasions
					%hr
					= render 'modaldiv'
					= yield
					.h1
						%small 
							Wishme-hub is specially designed to wish your family and friends in a better and different way. We have gif's for many occasions, and we always keep on adding more. All you need to do is write your name in the name box and press the
							%i
								wish
							button.

					.footer
						%footer
							.text-center
								%b Creator: ALAAP DHALL
								%br
								%i We appreciate your love, and suppor. please give your feedback and any suggestions.
								%br
							.text-center{'data-target':'#feedback' , 'data-toggle':'modal'}
								.btn.btn-primary.modallink.grey Feedback

				
				%marquee.col-xs-1{'direction':'down','scrolldelay:':'5'}
					=image_tag 'diwali1.png' , class:'marquee-right'
					%br
					=image_tag 'diwali2.png' , class:'marquee-right'
					%br
					=image_tag 'diwali1.png' , class:'marquee-right'
					%br
					=image_tag 'diwali2.png' , class:'marquee-right'
					%br
					=image_tag 'diwali1.png' , class:'marquee-right'
					%br
					=image_tag 'diwali2.png' , class:'marquee-right'
					%br
					=image_tag 'diwali1.png' , class:'marquee-right'
					%br
					=image_tag 'diwali2.png' , class:'marquee-right'
					%br
					=image_tag 'diwali1.png' , class:'marquee-right'
					%br
					=image_tag 'diwali2.png' , class:'marquee-right'
					%br
					=image_tag 'diwali1.png' , class:'marquee-right'
					%br
					=image_tag 'diwali1.png' , class:'marquee-right'
					%br

= render 'feedback'